title: SAFe Migration Project
description: Detailed guide and playbooks for SAFe transformation
theme: minima

# Настройки оформления
minima:
  skin: light

# Исключаем лишнее, чтобы сборка не ломалась
exclude: [node_modules, vendor]